---
- name: "A test for #41313. See https://github.com/ansible/ansible/issues/41313"
  hosts: localhost
  connection: local
  
#---
# PRE-TASKS
#---
  pre_tasks:
  - name: Shows Ansible version
    debug:
      msg:
      - "Playbook running Ansible version '{{ ansible_version.string }}'"
      - "This is always going to be the First Message."
      - "See tasks' sorting below..."

#---
# TASKS
#---
  tasks:
  - name: "First task (it triggers 'my_handler')"
    set_fact:
      my_task: "This comes from 'first_task'."
    changed_when: true  # make sure the handler is always notified
    notify: my_handler

  - name: "This 'flush_handlers' should NEVER be triggered as the 'when' clause ALWAYS evaluates to False!"
    meta: flush_handlers
    when: 1 == 2

  - name: Last task
    debug:
      msg:
      - 'This is the last task.'
      - "If 'flush_handlers' worked as it should, this would appear BEFORE the triggered handler!!!"

#---
# HANDLERS
#---
  handlers:
  - name: my_handler
    debug:
      msg:
      - "{{ my_task }}"
      - "If 'flush_handlers' worked as it should, this would be the LAST message!!!"
